### ISSUE TITLE
However, I need to verify it in the previous Safari browser. The cache has been cleared, so I cannot verify it. As a result, I cannot restore my account, what should I do

### ISSUE THREAD

**Issue by XuechengSong** [dfinity/agent-rs#181]
However, I need to verify it in the previous Safari browser. The cache has been cleared, so I cannot verify it. As a result, I cannot restore my account, what should I do

**Comment by XuechengSong** [comment]
I added the device in the Google browser on the same phone

**Comment by nomeata** [comment]
Sorry for these inconveniences. Would you submit a support request at https://support.dfinity.org/ for this? Closing this here, as this is not an issue with software in this repository.
