### ISSUE TITLE
Refactor `PrincipalError` to make `PrincipalBufferError` obsolete

### ISSUE THREAD

**Issue by hansl** [dfinity/agent-rs#193]
Using `String` in the `PrincipalError` type is blocking this work as it cannot be used in `const` functions. This means that we have a new error type which duplicated some errors from `PrincipalError`.

The fix is to make `PrincipalError` a type that can be returned by the const functions. There are two variants which use `String`:

- `ExternalError` which should be removed entirely. Having a custom holder of string is not very useful in this specific case.
- `AbnormalTextualFormat` which shows what a principal should look like (in case of formatting errors).

This last one can either be split in multiple error types with better information (like invalid checksum, groups, etc). Or it could contain a stack allocated `str`. Since principal textual format can only hold base32 chars (+ `-`s) this should be trivial to make (something like `[u8; MAX_LENGTH]`). Having fixed length slices though make this type bloat every `Result` return values, so this should be considered.

**Comment by Daniel-Bloom-dfinity** [comment]
Does `AbnormalTextualFormat` even need to store the string? The string is constructed as:
```rust
let expected = format!("{}", result);
// ...
return Err(PrincipalError::AbnormalTextualFormat(expected));
```

It seems like it could just store `result` (which is a `Principal`) instead of `expected`, since it's just a deterministic call to `format!`, which is already inherent in the `#[error]` annotation.

**Comment by hansl** [comment]
Yes, that sounds fine.
