### ISSUE TITLE
Unable to call "hello world" canister method using ic-agent rust snippet.

### ISSUE THREAD

**Issue by amitcz** [dfinity/agent-rs#253]
1. Deployed canister that returns some string when call from DFX. 
2. Created rust snippet using **ic_agent** .

Problem : When calling canister method from the rust code, it throws following error : 

```
error response:ReplicaError {
    reject_code: 5,
    reject_message: "IC0503: Canister qvhpv-4qaaa-aaaaa-aaagq-cai trapped explicitly: Custom(Cannot parse header \n\nCaused by:\n    binary parser error: io error)",
} 

```
I am sharing snipped and canister 
[Github link ](https://github.com/amitcz/canister-call-rust.git)

I think there is some issue with **ic_agent** ...
Hoping for some quick response from Dfinity team.

**Comment by roman-kashitsyn** [comment]
I believe the problem is that you don't provide the argument in your call.
In candid, empty byte sequence != empty argument list.

Try this in your main.rs:
```rust
    let response = agent.query(&canister_id, method_name).with_arg(candid::Encode!().unwrap()).call().await;
```

**Comment by amitcz** [comment]
Healthfully thanks @roman 

At least should be documented.
I am happy :)
