### ISSUE TITLE
why ic-agent  is not a [no-std] crate?

### ISSUE THREAD

**Issue by Nanue1** [dfinity/agent-rs#360]
I want to use rust to implement the front end. When I use ic-agent in wasm, I can't compile it normally.

**Comment by Nanue1** [comment]
hyper-rustls = { version = "0.23.0", features = [ "webpki-roots" ] }  @eric-swanson  
Is it because of this crate that ic-agent is no longer a no-std crate?

**Comment by Nanue1** [comment]
My wasm front-end program is running in chrome, I can't use ic-cdk, should ic-agent consider supporting no-std?

**Comment by Nanue1** [comment]
My wasm front-end program is running in chrome, I can't use ic-cdk, should ic-agent consider supporting no-std? @chenyan-dfinity

**Comment by chenyan-dfinity** [comment]
I'm confused. If you want to run in browser, why not use `agent-js`?

**Comment by smallstepman** [comment]
I think it's because they don't want to use JS at all 
> I want to use rust to implement the front end.

**Comment by Nanue1** [comment]
> I think it's because they don't want to use JS at all
> 
> > I want to use rust to implement the front end.

Yes, I'm trying to use the rust language for cross-platform development
