### ISSUE TITLE
Question: How to list transfers from a specified date?

### ISSUE THREAD

**Issue by ababo** [dfinity/agent-rs#381]
I'm really new to IC, so this question might be stupid. How can I list the blockchain transaction/transfers from a specified time using this crate's APIs?

**Comment by sesi200** [comment]
Generally speaking you will get better support over at forum.dfinity.org.

The entry point for all documentation regarding agent-rs is here: https://internetcomputer.org/docs/current/developer-docs/build/agents/ic-agent-dfinity/

As for how to query the ledger (that's the canister that contains the transactions), I recommend you look here: https://forum.dfinity.org/t/how-do-i-query-the-ledger-canister/7839

**Comment by ababo** [comment]
Thanks.
