### ISSUE TITLE
Make the default identity the anonymous user

### ISSUE THREAD

**Issue by luc-mercier** [dfinity/agent-rs#58]
Function `AgentBuilder::with_identity` has the following comment:

> This is required.

https://github.com/dfinity/agent-rs/blob/a921a935a4579f6e2c13a9a360795479be7f6c02/ic-agent/src/agent/builder.rs#L42

It should not be required. By default, it should use the anonymous user. The spec reads:
https://docs.dfinity.systems/public/#authentication

> The fields sender_pubkey and sender_sig must be omitted if and only if the sender field is absent or the anonymous principal.

**Comment by nomeata** [comment]
I’ll leave the design of this library to those who wrote it, but I’d like to comment that is is totally valid for the agent to choose to make the sender required, and thus make the user _explicitly_ set the anonymous sender with `with_identity`, or maybe a separate `as_anonymous`.

So I’d say this issue should be called “make it possible to do queries as the anonymous user”, and leave it to those who design the library to decide how to best support that requirement.

**Comment by Dfinity-Bjoern** [comment]
On a related note, this PR https://github.com/dfinity-lab/ic-ref/pull/203 changes the spec so that for anonymous requests, the sender must also be set (to `0x04`).

**Comment by nomeata** [comment]
Actually, looking at the code `with_identity(DummyIdentity)` should do the required thing. So maybe nothing needs to be done here?

**Comment by luc-mercier** [comment]
> Actually, looking at the code `with_identity(DummyIdentity)` should do the required thing. So maybe nothing needs to be done here?

Does it? https://github.com/dfinity/agent-rs/blob/0aa801d154c8bd47eefb101802f1a21e14e1e93b/ic-agent/src/identity/dummy.rs#L14-L15 looks like they don't match the spec

**Comment by nomeata** [comment]
Indeed, seems like support is not complete. Also, 
```
        let sender = match &request {
            SyncContent::QueryRequest { sender, .. } => sender,
            SyncContent::RequestStatusRequest { .. } => &anonymous,
        };
```
looks broken; tha anonymous user will usually not be allowed to read the status of a request (unless that request was issued by the anonymous user). I wonder why this is even working…
